import { MainProvider } from "@/utils/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "u-zero",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MainProvider>
        <body
          className={`${geistSans.variable} antialiased mx-auto w-1/2 p-4 m-10 h-screen`}
        >
          {children}
        </body>
      </MainProvider>
    </html>
  );
}
